# Generated by Django 5.1.4 on 2025-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='closed',
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em andamento'), ('on_hold', 'Em espera'), ('cancelled', 'Cancelada'), ('pending', 'Pendente'), ('done', 'Concluida')], default='in_progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'A fazer'), ('in_progress', 'Em andamento'), ('on_hold', 'Em espera'), ('cancelled', 'Cancelada'), ('pending', 'Pendente'), ('done', 'Concluida')], default='todo', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
